In [26]:
import sys
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.append(str(PROJECT_ROOT))

In [27]:
import pandas as pd

from src.metrics import Metrics
from src.models.TFIDFBaseline import TFIDFBaseline

In [28]:
train_df = pd.read_csv("../data/processed/train.csv")

train_df.head()

,question1,question2,is_duplicate
0,what is the fastest way to memorise a huge amo...,what is the best and fastest way to memorize a...,0
1,when marie antoinette famously didn t say let ...,do nmat and snap have algebra in its,0
2,who makes the best hummus in israel,who makes the best hummus,0
3,what are the top it schools in the philippines,what are the best schools in the philippines,0
4,why are the tides different in some places tha...,can a place be in two different places at once,0

In [29]:
val_df = pd.read_csv("../data/processed/val.csv")

val_df.head()

,question1,question2,is_duplicate
0,what are some poems about heaven,what should a poem be about,0
1,why can t i just cry,why do we cry,0
2,how much is the average cost to replace an alt...,where can i get my car s alternator replaced a...,0
3,most of us are never going to be famous i m mi...,my present roommate at first asked about shari...,0
4,what is best place to buy luxury apartments in...,what are some common applications for communic...,0

In [30]:
model_on_logreg = TFIDFBaseline()
model_on_logreg.fit(train_df, mode="logreg")

y_pred_on_logreg = model_on_logreg.predict(val_df)
y_proba_on_logreg = model_on_logreg.predict_proba(val_df)
y_true = val_df["is_duplicate"]

logreg_report = Metrics.report(
    y_true=y_true,
    y_pred=y_pred_on_logreg,
    y_score=y_proba_on_logreg,
    k=0.1,
)

print(logreg_report)

{'accuracy': 0.8032486807387863, 'roc_auc': 0.892641284186743, 'precision_at_k': 0.9437664907651715}

In [31]:
model_on_cosine = TFIDFBaseline()
model_on_cosine.fit(train_df, mode="cosine")

y_pred_on_cosine = model_on_cosine.predict(val_df)
y_proba_on_cosine = model_on_cosine.predict_proba(val_df)
y_true = val_df["is_duplicate"]

cosine_report = Metrics.report(
    y_true=y_true,
    y_pred=y_pred_on_cosine,
    y_score=y_proba_on_cosine,
    k=0.1,
)

print(cosine_report)

{'accuracy': 0.6098614775725594, 'roc_auc': 0.6586042590208631, 'precision_at_k': 0.5629947229551451}